program ::= omessage | imessage ;
omessage ::= ( omail %w* )+ %w* optmore? %w* ;
optmore ::= "{MORE}" ;

omail ::=  "To:" %w* ...name %w* body ;

imessage ::= ( imail %w* )+ ;

imail ::=  "From:" %w* ...name %w* body ;


body ::= %"\n"* ( line %"\n"* )+ ;
  line ::= ...any* ;

name ::= ...( letter | digit | "_" )+ ;
  letter ::= "a"->"z" | "A"->"Z" ;
  digit ::= "0"->"9" ;

# Whitespace
w ::= " " | "\t" | "\n" | "\r" ;

# Consumes a single wild character
any ::= !"" ;
