program ::= message | repl ;
repl ::= orepl | irepl ;
message ::= omessage | imessage ;
omessage ::= "📧" ( omail %w* )+ %w* optmore? %w* ;
optmore ::= "{MORE}" ;

omail ::=  "To:" %w* ...person %w* lines ;

imessage ::= ( imail %w* )+ ;

imail ::=  "From:" %w* ...person %w* lines ;

orepl ::= "🖥️" lines ;
irepl ::= replname ">" %w* (lines)? ;
replname ::= "node" | "bash" | "js" | "sqlite" ;


lines ::= %"\n"* ( line %"\n"* )+ ;
  line ::= ...any* ;

person ::= ...( letter | digit | "_" )+ ;
  letter ::= "a"->"z" | "A"->"Z" ;
  digit ::= "0"->"9" ;



# Whitespace
w ::= " " | "\t" | "\n" | "\r" ;

# Consumes a single wild character
any ::= !"" ;
